CREATE DATABASE HEALTHCARE_DATABASE;

USE HEALTHCARE_DATABASE;

-- View all records;
SELECT * FROM Healthcare;

-- DESCRIBE THE TABLE;
DESCRIBE Healthcare;

-- TOP 5 MOST COMMON MEDICAL CONDITION
CREATE VIEW MEDICAL_CONDITION AS 
SELECT Medical_condition, count(*) AS NUM_OF_CASES
FROM healthcare
GROUP BY MEDICAL_CONDITION
ORDER BY NUM_OF_CASES DESC 
LIMIT 5;

-- TOTAL BILLING AMOUNT BY INSURANCE PROVIDER
CREATE VIEW BILLING_AMOUNT_BY_IP AS
SELECT INSURANCE_PROVIDER, sum(BILLING_AMOUNT) AS TOTAL_BILLS
FROM healthcare
GROUP BY INSURANCE_PROVIDER
ORDER BY TOTAL_BILLS DESC;

-- AVERAGE LENGTH OF STAY BY CONDITION
CREATE VIEW AVERAGE_STAY_BY_CONDITION AS 
SELECT MEDICAL_CONDITION, avg(DATEDIFF(DISCHARGE_DATE,DATE_OF_ADMISSION)) AS AVG_STAY_DAYS
FROM healthcare
GROUP BY MEDICAL_CONDITION
ORDER BY AVG_STAY_DAYS DESC;

-- MONTHLY ADMISSION TREND
CREATE VIEW MONTHLY_TREND AS 
SELECT month(DATE_OF_ADMISSION) AS MONTH, count(*) AS NUM_OF_ADMISSION
FROM healthcare
GROUP BY month
ORDER BY MONTH;

-- GENDER DISTRIBUTION BY CONDITION
CREATE VIEW GENDER_DISTRIBUTION AS
SELECT MEDICAL_CONDITION, GENDER, count(*) AS COUNT
FROM healthcare
GROUP BY MEDICAL_CONDITION, GENDER
ORDER BY MEDICAL_CONDITION,COUNT DESC;

-- PATIENTS WITH ABNORMAL TEST RESULTS AND HIGH BILLING
CREATE VIEW PATIENTS_RESULT_BY_BILLIING AS 
SELECT NAME, TEST_RESULTS, BILLING_AMOUNT
FROM healthcare
WHERE TEST_RESULTS = "ABNORMAL" AND BILLING_AMOUNT > 30000
ORDER BY BILLING_AMOUNT DESC;
